### ISSUE TITLE
Encryption detection failed?

### ISSUE THREAD

**Issue by Tsaukpaetra** [dakkshesh07/recovery_device_realme_rmx1921#1]
Thank you for getting the recovery working. One thing I seem to be encountering is that the encryption of `/data` isn't being detected. I'm not entirely sure if the problem is with Android 13 or something more simple.

**Comment by beakthoven** [comment]
> Thank you for getting the recovery working. One thing I seem to be encountering is that the encryption of `/data` isn't being detected. I'm not entirely sure if the problem is with Android 13 or something more simple.

Sorry for late reply, I had been inactive on this project for a long time. I will look into the problem but as far as i remember i had no issues with encryption on Android 13

**Comment by Tsaukpaetra** [comment]
Yeah if it helps I'm on AncientOS-13-TexasCake-v7.2. I can tell the partition is mounted and presumably back-up-able but decryption just isn't attempted at all so you just see the cypher stuff. Not super important since it seems there may not be a maintainer for this particular ROM anymore (two minor versions behind at the moment).

**Comment by beakthoven** [comment]
> Yeah if it helps I'm on AncientOS-13-TexasCake-v7.2. I can tell the partition is mounted and presumably back-up-able but decryption just isn't attempted at all so you just see the cypher stuff. Not super important since it seems there may not be a maintainer for this particular ROM anymore (two minor versions behind at the moment).

Well if i remember correctly AncientOS rom was using non retrofit partitions along with ext4. I had made this recovery for solely working with my PixelOS roms because of the extra requirements it needed for flashing retrofit f2fs roms.

**Comment by Tsaukpaetra** [comment]
Ah, that makes sense if the expected formats aren't matching. This was just the only one I had found that actually booted correctly on my phone well enough to actually flash the ROM . It seems there may not be a maintainer for OrangeFox for rmx1912 anymore so I had to dig around. 😇

**Comment by beakthoven** [comment]
> Ah, that makes sense if the expected formats aren't matching. This was just the only one I had found that actually booted correctly on my phone well enough to actually flash the ROM . It seems there may not be a maintainer for OrangeFox for rmx1912 anymore so I had to dig around. 😇

There are other ofox builds by other maintainers adjusted for their roms, i would recommend using those and with that i will close this issue.
